#!/usr/bin/env bash
# This commit message hook is inspired on the one in ITK.

egrep-q() {
  egrep "$@" >/dev/null 2>/dev/null
}

# Prepare a copy of the message:
#  - strip comment lines
#  - stop at "diff --git" (git commit -v)
git_dir=$(git rev-parse --git-dir)
commit_msg=$git_dir/COMMIT_MSG
sed -n -e '/^#/d' -e '/^diff --git/q' -e 'p;d' "$1" > "$commit_msg"

die() {
  echo 'commit-msg hook failure' 1>&2
  echo '-----------------------' 1>&2
  echo '' 1>&2
  echo "$@" 1>&2
  echo '
To continue editing, run the command
  git commit -e -F '"$commit_msg"'
(assuming your working directory is at the top).' 1>&2
  exit 1
}

# Check the first line for a standard prefix.
cat "$commit_msg" |
while IFS='' read line; do
  # Look for the first non-empty line.
  len=$(echo -n "$line" | wc -c)
  if test $len -gt 0; then
    # Look for valid prefixes.
    echo "$line" |
    egrep-q '^(Merge|Revert|BUG:|COMP:|DOC:|ENH:|PERF:|STYLE:|WIP:) ' ||
    die 'Start commit messages with a standard prefix (and a space):
  BUG:    - fix for runtime crash or incorrect result
  COMP:   - compiler error or warning fix
  DOC:    - documentation change
  ENH:    - new functionality
  PERF:   - performance improvement
  STYLE:  - no logic impact (indentation, comments)
  WIP:    - Work In Progress not ready for merge'

    # Done.  Skip rest of lines.
    break
  fi
done &&
rm -f "$commit_msg" || exit 1
